#Better Fishtanks Mod Configuration
[general]
	#Require food for fish survival
	requireFood = true
	#Defines how water is displayed in Fish Tank UI
	#PERCENT: Shows as percentage (0-100%)
	#BUCKETS: Shows as whole buckets (B)
	#MILLIBUCKETS: Shows as millibuckets (mB)
	#Allowed Values: PERCENT, BUCKETS, MILLIBUCKETS
	waterDisplayUnit = "PERCENT"
	#BETA MODE Set to true to use the new entity-based water rendering system.
	#Set to false to use the vanilla waterlogging system.
	useEntityWaterRendering = false

[mob]
	#Set to true to allow Drowned to be captured with the Fish Bag.
	allowDrownedCapture = false
	#Set to true to allow Guardians and Elder Guardians to be captured with the Fish Bag.
	allowGuardianCapture = false
	#Set to true to allow whales to be captured with the Fish Bag.
	#WARNING: Large fish like whales may eat smaller fish in the same tank!
	allowWhaleCapture = false
	#Set to false to prevent fish from hunting or hurting each other inside the fishtank.
	allowFishHunting = true
	#Set to false to prevent pufferfish from blowing up while in a fishtank.
	allowPufferfishPuffing = true
