#.
#Hide backslashes placed before the disabled placeholders.
hideEscapingOfDisabledPlaceholders = false
#.
#Allow usage of placeholders for the Progress Bar display format (the bar characters will incorrectly appear as non-wide).
enableProgressBarPlaceholdersSupport = false

#.
#Placeholders Settings
[placeholdersSettings]
	#.
	#Treat {} (curly brackets) as a placeholder for the Attached Label.
	enableCurlyBracketsPlaceholder = true
	#.
	#Treat $ (dollar sign) as a placeholder for the Attached Label.
	enableDollarSignPlaceholder = true

#.
#Display Source Settings
[displaySourceSettings]
	#.
	#Add Attached Label functionality to the Current Floor display source from Create.
	enhanceCurrentFloorDisplaySource = true
	#.
	#Add Attached Label functionality to the Train Status display source from Create.
	enhanceTrainStatusDisplaySource = true
