#.
#Display Link GUI
[displayLinkGUI]
	#.
	#Show the 'Placeholders Usage Guide' & 'Duplicating Display Link Properties' buttons in Display Link interface.
	enableGuideButtons = true
	#.
	#Allow the guide buttons to redirect to their respective Ponder scenes on clicked.
	#Only takes effect if 'Enable Guide Buttons' is enabled.
	enableGuideButtonRedirects = true

	#.
	#Guide Tooltips Customization
	[displayLinkGUI.guideTooltipsCustomization]
		#.
		#Show the Active placeholders part of the Placeholders Usage Guide tooltip.
		enableActivePlaceholdersTooltip = true
		#.
		#Show the Progress Bar display format support part of the Placeholders Usage Guide tooltip.
		enableProgressBarSupportStateTooltip = true

#.
#Clipboard Display Source GUI
[clipboardDisplaySourceGUI]
	#.
	#Prevent the 'Copy the Attached Label' from being automatically selected if the Attached Label is empty.
	deselectEmptyAttachedLabel = true

#.
#Clipboard Display Link Outlines
[clipboardDisplayLinkOutlines]
	#.
	#Enable a green block outline for Display Links when holding a Clipboard that is different from other components which properties can be copied.
	enableCustomOutlineForDisplayLinks = true
	#.
	#Color the block outline red for Display Links with invalid Source block or Target position data.
	#Only takes effect if 'Enable Custom Outline For Display Links' is enabled.
	enableDifferentOutlineForInvalidDisplayLinks = true
	#.
	#The opacity of custom block outlines for Display Links.
	#It's set to 0.4 for other components which properties can be copied with a Clipboard.
	#Only takes effect if 'Enable Custom Outline For Display Links' is enabled.
	# Default: 0.800000011920929
	# Range: 0.0 ~ 1.0
	customOutlineAlpha = 0.800000011920929

#.
#Text Fields Enhancements
[textFieldsEnhancements]
	#.
	#Hide the overflowing ends of long strings to make them fit into their text fields.
	truncateOverflowingStrings = true
	#.
	#Add the 'Marquee' (AKA 'Running Line') effect to the truncated strings.
	#Only takes effect if 'Truncate Overflowing Strings' is enabled.
	addMarqueeEffectToTruncatedStrings = true
	#.
	#Show the 'Type of Information' selector tooltip if it only has a single option.
	#Only takes effect if 'Truncate Overflowing Strings' is enabled.
	showTooltipForSingleOptionSelector = true

	#.
	#Marquee Effect Settings
	[textFieldsEnhancements.marqueeEffectSettings]
		#.
		#[in Milliseconds]
		#The fixed time for the truncated string to scroll through, per overflowing character.
		# Default: 30
		# Range: 1 ~ 10000
		fixedCharTravelTime = 30
		#.
		#[in Seconds]
		#The fixed time for the truncated string to scroll through, independently of its length.
		#Overrides 'Fixed Char Travel Time' and 'Maximal/Minimal String Travel Time'.
		#Set to zero (0.0) to disable.
		# Default: 0.0
		# Range: 0.0 ~ 600.0
		fixedStringTravelTime = 0.0
		#.
		#[in Seconds]
		#The maximal time for the truncated string to scroll through, independently of its length.
		#Set to zero (0.0) to disable.
		# Default: 0.0
		# Range: 0.0 ~ 600.0
		maximalStringTravelTime = 0.0
		#.
		#[in Seconds]
		#The minimal time for the truncated string to scroll through, independently of its length.
		#Set to zero (0.0) to disable.
		# Default: 0.0
		# Range: 0.0 ~ 60.0
		minimalStringTravelTime = 0.0
		#.
		#[in Seconds]
		#The fixed time for the truncated string to stay still once at the start or the end of scrolling.
		# Default: 2.0
		# Range: 0.0 ~ 600.0
		stringPauseTime = 2.0
